spring.application.name=reservapalcos
spring.datasource.url=jdbc:postgresql://localhost:5432/reservapalcos
spring.datasource.username=postgres
spring.datasource.password=olakase12
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never