spring.application.name=reservapalcos
spring.datasource.url=jdbc:postgresql://localhost:5432/reservapalcos
spring.datasource.username=postgres
spring.datasource.password=olakase12
app.security.remember-me-key=3b1e5a2f-7e91-4f4b-9c11-7f8d42c9eab5
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
